#!/usr/bin/env python3
"""
빌드 번호 업데이트 스크립트.

커밋 전에 실행:
  python3 scripts/update_build.py
  git add znc/_build_info.py
"""
import subprocess, os, re

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

count = subprocess.check_output(
    ["git", "rev-list", "--count", "HEAD"], cwd=root, text=True
).strip()

# 현재 커밋 수 + 1 (이 커밋이 추가될 예정)
build = int(count) + 1

out = os.path.join(root, "znc", "_build_info.py")
with open(out, "w") as f:
    f.write("# Auto-generated by scripts/update_build.py — do not edit manually\n")
    f.write(f"BUILD_NUMBER = {build}\n")

print(f"Build number updated: {build}")
